/**
 * @file confirmation.js
 * @description Accessible Human Confirmation & Consent Layer for Handrail.
 *
 * ABSOLUTE SECURITY & ACCESSIBILITY PRINCIPLES:
 * 1. Authority must be checked inside the tool's own execute() function BEFORE reaching this layer.
 * 2. Confirmation MUST NOT grant authority.
 * 3. Confirmation ONLY confirms an action that is ALREADY within the user's authority.
 * 4. Out-of-scope requests are blocked at Gate 2 and NEVER open this confirmation dialog.
 * 5. Confirmation content is derived EXCLUSIVELY from the tool's declared schema and actual structured arguments,
 *    NEVER from unverified natural-language text generated by an AI agent.
 * 6. The confirmation must clearly communicate:
 *    - what action will happen
 *    - which medication
 *    - relevant declared arguments
 *    - amount if applicable
 *    - why confirmation is required
 *    - what approving means
 *    - what denying means
 * 7. Focus is trapped within the modal while open, and restored to the triggering element upon close.
 * 8. Escape safely closes and denies the request without side effects.
 */

let activeResolve = null;
let previousActiveElement = null;
let customConfirmationProvider = null;
let stopwatchStartTime = null;
let stopwatchInterval = null;
let stopwatchElement = null;

/**
 * Sets a custom confirmation provider function for test environments or headless execution.
 * @param {((payload: object) => Promise<{ confirmed: boolean, reason?: string, timestamp?: string }>)|null} provider
 */
export function setConfirmationProvider(provider) {
  customConfirmationProvider = provider;
}

/**
 * Resets the confirmation provider back to standard browser DOM modal.
 */
export function resetConfirmationProvider() {
  customConfirmationProvider = null;
}

/**
 * Initializes the confirmation dialog system and keyboard listeners.
 */
export function initConfirmationSystem() {
  if (typeof document === 'undefined') return;

  const dialog = document.getElementById('handrail-confirmation-dialog');

  // Create unobtrusive stopwatch element (aria-hidden: visual only, no screen reader interference)
  if (dialog && !document.getElementById('dialog-stopwatch')) {
    stopwatchElement = document.createElement('span');
    stopwatchElement.id = 'dialog-stopwatch';
    stopwatchElement.setAttribute('aria-hidden', 'true');
    stopwatchElement.style.cssText = 'display:inline-block;margin-left:8px;font-family:monospace;font-size:0.75rem;color:var(--color-text-muted, #64748b);vertical-align:middle;';
    const titleEl = document.getElementById('dialog-title');
    if (titleEl && titleEl.parentNode) {
      titleEl.parentNode.insertBefore(stopwatchElement, titleEl.nextSibling);
    }

    // Placeholder for real baseline comparison (to be supplied after user testing)
  }

  const cancelBtn = document.getElementById('dialog-deny-btn');
  const confirmBtn = document.getElementById('dialog-authorize-btn');

  if (cancelBtn) {
    cancelBtn.addEventListener('click', () => handleDecision(false, 'User clicked Deny'));
  }

  if (confirmBtn) {
    confirmBtn.addEventListener('click', () => handleDecision(true, 'User clicked Approve refill'));
  }

  if (dialog) {
    dialog.addEventListener('cancel', (e) => {
      e.preventDefault();
      handleDecision(false, 'User dismissed with Escape key');
    });

    // Keyboard trap and Escape handling inside dialog
    dialog.addEventListener('keydown', (e) => {
      if (e.key === 'Escape') {
        e.preventDefault();
        handleDecision(false, 'User pressed Escape key');
        return;
      }

      if (e.key === 'Tab') {
        const focusableElements = Array.from(
          dialog.querySelectorAll(
            'button:not([disabled]), [href], input:not([disabled]), select:not([disabled]), textarea:not([disabled]), [tabindex]:not([tabindex="-1"]), summary'
          )
        );
        if (focusableElements.length === 0) return;

        const firstElement = focusableElements[0];
        const lastElement = focusableElements[focusableElements.length - 1];

        if (e.shiftKey) {
          if (document.activeElement === firstElement) {
            e.preventDefault();
            lastElement.focus();
          }
        } else {
          if (document.activeElement === lastElement) {
            e.preventDefault();
            firstElement.focus();
          }
        }
      }
    });
  }
}

/**
 * Formats a structured object for auditable schema display.
 * @param {object} args
 * @returns {string}
 */
function formatAuditableArguments(args = {}) {
  const entries = Object.entries(args).filter(([_, v]) => v !== undefined && v !== null);
  if (entries.length === 0) return '  (No additional arguments provided)';
  return entries
    .map(([k, v]) => `  ${k}: ${Array.isArray(v) ? `[${v.join(', ')}]` : typeof v === 'object' ? JSON.stringify(v) : v}`)
    .join('\n');
}

/**
 * Prompts the user with an accessible confirmation dialog.
 * @param {object} payload - Action, policy reason, and medication details
 * @returns {Promise<{ confirmed: boolean, reason: string, timestamp: string }>}
 */
export function requestHumanConfirmation(payload) {
  // If a custom confirmation provider is registered (e.g., in automated tests or headless agent runner), invoke it directly
  if (typeof customConfirmationProvider === 'function') {
    return Promise.resolve()
      .then(() => customConfirmationProvider(payload))
      .then((res) => {
        if (!res || typeof res !== 'object') {
          return { confirmed: false, reason: 'Custom confirmation provider returned invalid response (Fail Closed)', timestamp: new Date().toISOString() };
        }
        return {
          confirmed: res.confirmed === true,
          reason: res.reason || (res.confirmed ? 'Authorized via test provider' : 'Denied via test provider'),
          timestamp: res.timestamp || new Date().toISOString(),
        };
      })
      .catch((err) => {
        return {
          confirmed: false,
          reason: `Confirmation provider threw exception: ${err.message} (Fail Closed)`,
          timestamp: new Date().toISOString(),
        };
      });
  }

  return new Promise((resolve) => {
    if (typeof document === 'undefined') {
      // Fail closed when running in headless / non-DOM environment with no custom provider
      resolve({
        confirmed: false,
        reason: 'Confirmation unavailable (Headless / non-DOM environment with no confirmation provider configured). Failing closed.',
        timestamp: new Date().toISOString(),
      });
      return;
    }

    activeResolve = resolve;
    previousActiveElement = document.activeElement;

    const dialog = document.getElementById('handrail-confirmation-dialog');
    const titleEl = document.getElementById('dialog-title');
    const descEl = document.getElementById('dialog-description');
    const detailsContainer = document.getElementById('dialog-action-details');
    const announcer = document.getElementById('accessibility-announcer');

    if (!dialog) {
      console.warn('Confirmation dialog element missing; fallback to denial.');
      resolve({ confirmed: false, reason: 'Dialog element missing from DOM. Failing closed.', timestamp: new Date().toISOString() });
      return;
    }

    const { action, reason, details } = payload;
    const toolName = action || 'submit_refill';
    const calc = details?.calculation || details;
    const items = calc?.items || [];
    const totalCost = calc?.totalCost !== undefined ? calc.totalCost : (details?.cost || 0);
    const structuredArgs = details?.structuredArgs || {};
    const maxSpendLimit = details?.maxSpendLimit !== undefined ? details.maxSpendLimit : (details?.threshold || 25.0);
    const threshold = details?.confirmationThreshold !== undefined ? details.confirmationThreshold : (details?.threshold || 10.0);

    const deliveryMethod = structuredArgs.deliveryMethod || details?.deliveryMethod || calc?.deliveryMethod || 'pickup';
    const quantity = structuredArgs.quantity || details?.quantity || (items[0]?.requestedQuantity || items[0]?.quantity || 30);
    const refillReason = structuredArgs.refillReason || details?.refillReason || null;
    const patientNote = structuredArgs.patientNote || details?.patientNote || null;
    const urgency = structuredArgs.urgency || details?.urgency || null;

    let deliveryMethodLabel = 'In-Store Pickup (RefillRx Downtown Hub #104)';
    if (deliveryMethod === 'delivery') deliveryMethodLabel = 'Home Delivery (Patient Address on File)';
    if (deliveryMethod === 'mail') deliveryMethodLabel = 'USPS Priority Mail Pharmacy Order';

    const medNamesText = items.map((i) => `${i.medication} ${i.dosage}`).join(', ') || 'Prescription item';
    const formattedCost = `$${Number(totalCost).toFixed(2)}`;

    const requireConfirmFlag = details?.requireHumanConfirmation === true;
    const exceedsThreshold = details?.costExceedsThreshold === true || (totalCost >= threshold);

    // Build accurate explanation for why confirmation is required
    let confirmationReasonText = '';
    if (requireConfirmFlag && exceedsThreshold) {
      confirmationReasonText = `Handrail policy requires human confirmation because this is a <strong>mutating pharmacy transaction</strong> and the copay (${formattedCost}) meets or exceeds your consent threshold ($${Number(threshold).toFixed(2)}).`;
    } else if (requireConfirmFlag) {
      confirmationReasonText = `Handrail policy requires human confirmation because this is a <strong>mutating pharmacy transaction</strong> and your authority contract has <strong>require human confirmation</strong> enabled. The copay (${formattedCost}) is below your $${Number(threshold).toFixed(2)} threshold, but confirmation is still required by policy.`;
    } else if (exceedsThreshold) {
      confirmationReasonText = `Handrail policy requires human confirmation because the copay (${formattedCost}) meets or exceeds your consent threshold ($${Number(threshold).toFixed(2)}).`;
    } else {
      confirmationReasonText = `Handrail policy requires human confirmation for this <strong>mutating pharmacy transaction</strong>.`;
    }

    if (titleEl) {
      titleEl.textContent = `Step 4: Confirm Prescription Refill — ${medNamesText}`;
    }

    if (descEl) {
      descEl.textContent = `Human authorization required. ${reason || `Action: Submit refill order for ${medNamesText} (${formattedCost}).`}`;
    }

    if (detailsContainer) {
      const medicationLines = items.map((item) => {
        const itemQty = item.requestedQuantity || item.quantity || quantity;
        const itemPrice = item.calculatedPrice !== undefined ? item.calculatedPrice : item.price;
        return `
          <li class="dialog-item" style="padding: 10px 0; border-bottom: 1px solid var(--color-border);">
            <div>
              <strong style="color: var(--color-text-main); font-size: 0.95rem;">${item.medication} ${item.dosage}</strong>
              <div style="font-size: 0.8125rem; color: var(--color-text-muted); margin-top: 2px;">
                Quantity: ${itemQty} day supply &bull; Rx ID: <code>${item.id}</code>
              </div>
            </div>
            <span class="item-cost" style="font-weight: 700; color: var(--color-text-main); font-family: monospace;">$${Number(itemPrice).toFixed(2)}</span>
          </li>
        `;
      }).join('');

      const rawArgumentsFormatted = formatAuditableArguments({
        ...(items.length === 1 ? { prescriptionId: items[0].id } : { prescriptionIds: items.map((i) => i.id) }),
        quantity,
        deliveryMethod,
        ...(refillReason ? { refillReason } : {}),
        ...(patientNote ? { patientNote } : {}),
        ...(urgency ? { urgency } : {}),
      });

      detailsContainer.innerHTML = `
        <div class="confirmation-summary-box">
          <!-- 1. What action will happen -->
          <div class="confirmation-section-item" style="margin-bottom: 0.875rem;">
            <span class="field-label" style="display: block; font-weight: 700; font-size: 0.75rem; text-transform: uppercase; color: var(--color-text-muted);">
              1. What Action Will Happen
            </span>
            <p style="font-size: 0.9375rem; color: var(--color-text-main); margin-top: 2px;">
              The AI agent is requesting to <strong>submit a prescription refill order</strong> to RefillRx Pharmacy.
            </p>
          </div>

          <!-- 2. Medication -->
          <div class="confirmation-section-item" style="margin-bottom: 0.875rem;">
            <span class="field-label" style="display: block; font-weight: 700; font-size: 0.75rem; text-transform: uppercase; color: var(--color-text-muted);">
              2. Medication
            </span>
            <ul class="summary-list" aria-label="Requested Prescriptions" style="list-style: none; padding: 0; margin: 0.35rem 0 0.5rem 0;">
              ${medicationLines || `<li>${toolName}</li>`}
            </ul>
          </div>

          <!-- 3. Amount -->
          <div class="summary-total-row" style="display: flex; justify-content: space-between; align-items: baseline; margin: 0.875rem 0; padding: 8px 0; border-top: 2px solid var(--color-border); border-bottom: 2px solid var(--color-border);">
            <span class="total-label" style="font-weight: 700; color: var(--color-text-main);">3. Total Estimated Copay Amount:</span>
            <strong class="total-amount" style="font-size: 1.25rem; color: var(--color-text-main); font-family: monospace;">${formattedCost}</strong>
          </div>

          <!-- 4. Why confirmation is required -->
          <div class="confirmation-section-item" style="margin-bottom: 0.875rem; background: var(--color-warning-bg); border: 1px solid var(--color-warning-border); padding: 10px; border-radius: var(--radius-sm);">
            <span class="field-label" style="display: block; font-weight: 700; font-size: 0.75rem; text-transform: uppercase; color: var(--color-warning);">
              4. Why Confirmation Is Required
            </span>
            <p style="font-size: 0.875rem; color: var(--color-text-main); margin-top: 2px; line-height: 1.4;">
              ${confirmationReasonText}
            </p>
          </div>

          <!-- 5. What approving/denying means -->
          <div class="confirmation-section-item" style="margin-bottom: 0.875rem; display: grid; grid-template-columns: 1fr 1fr; gap: 0.75rem;">
            <div style="background: var(--color-success-bg); border: 1px solid var(--color-success-border); padding: 10px; border-radius: var(--radius-sm);">
              <strong style="font-size: 0.8125rem; color: var(--color-success); display: block; margin-bottom: 2px;">
                ✓ What Approving Means
              </strong>
              <p style="font-size: 0.8125rem; color: var(--color-text-main); line-height: 1.35; margin: 0;">
                Submits the refill order to RefillRx Pharmacy, prepares fulfillment, and charges your ${formattedCost} copay.
              </p>
            </div>
            <div style="background: var(--color-danger-bg); border: 1px solid var(--color-danger-border); padding: 10px; border-radius: var(--radius-sm);">
              <strong style="font-size: 0.8125rem; color: var(--color-danger); display: block; margin-bottom: 2px;">
                ✕ What Denying Means
              </strong>
              <p style="font-size: 0.8125rem; color: var(--color-text-main); line-height: 1.35; margin: 0;">
                Immediately cancels the agent's request. No prescription will be ordered, no money charged, and no records changed.
              </p>
            </div>
          </div>

          <!-- Collapsible Details section -->
          <details class="dialog-details-section" style="margin-top: 0.75rem; border: 1px solid var(--color-border); border-radius: var(--radius-sm); overflow: hidden;">
            <summary style="cursor: pointer; padding: 10px 12px; font-weight: 600; font-size: 0.8125rem; color: var(--color-text-main); background: var(--color-surface-subtle);">
              Details
            </summary>
            <div style="padding: 12px; font-size: 0.8125rem; line-height: 1.5;">
              <!-- Fulfillment & Authority -->
              <div style="margin-bottom: 0.75rem;">
                <span style="color: var(--color-text-muted); font-weight: 600;">Fulfillment:</span>
                <strong style="color: var(--color-text-main); margin-left: 4px;">${deliveryMethodLabel}</strong>
              </div>
              <div style="margin-bottom: 0.75rem;">
                <span style="color: var(--color-text-muted); font-weight: 600;">Authority Scope Check:</span>
                <span style="color: var(--color-text-main); margin-left: 4px;">
                  Within your authorized spend cap of <strong>$${Number(maxSpendLimit).toFixed(2)}</strong>.
                </span>
              </div>

              <!-- Auditable Schema Representation -->
              <div style="background: #0f172a; color: #f8fafc; border-radius: var(--radius-sm); padding: 10px; font-family: monospace; font-size: 0.75rem;">
                <div style="color: #94a3b8; font-weight: 600; margin-bottom: 6px;">Auditable Structured Parameters</div>
                <pre style="margin: 0; white-space: pre-wrap; font-family: monospace; font-size: 0.75rem; color: #38bdf8;">Tool:
${toolName}

Arguments:
${rawArgumentsFormatted}</pre>
              </div>
            </div>
          </details>
        </div>
      `;
    }

    // Accessible screen reader announcement
    if (announcer) {
      announcer.textContent = `Alert: Human confirmation required for ${toolName}. Action: Refill order for ${medNamesText} costing ${formattedCost}. Approving places the order; denying halts the agent. Press Tab to review or activate Approve or Deny buttons.`;
    }

    // Start confirmation response timer
    stopwatchStartTime = Date.now();
    if (stopwatchElement) {
      stopwatchElement.textContent = '⏱ 0.0s';
      stopwatchInterval = setInterval(() => {
        if (stopwatchElement && stopwatchStartTime) {
          const elapsed = ((Date.now() - stopwatchStartTime) / 1000).toFixed(1);
          stopwatchElement.textContent = `⏱ ${elapsed}s`;
        }
      }, 100);
    }

    if (typeof dialog.showModal === 'function') {
      dialog.showModal();
    } else {
      dialog.setAttribute('open', 'true');
    }

    // Move focus into the primary confirmation button
    const confirmBtn = document.getElementById('dialog-authorize-btn');
    if (confirmBtn) {
      confirmBtn.focus();
    }
  });
}

/**
 * Resolves the active confirmation promise and closes the modal.
 * @param {boolean} confirmed
 * @param {string} note
 */
function handleDecision(confirmed, note) {
  const dialog = document.getElementById('handrail-confirmation-dialog');
  const announcer = document.getElementById('accessibility-announcer');

  // Stop the timer and capture elapsed time
  let elapsedSeconds = null;
  if (stopwatchStartTime) {
    elapsedSeconds = ((Date.now() - stopwatchStartTime) / 1000).toFixed(1);
    stopwatchStartTime = null;
  }
  if (stopwatchInterval) {
    clearInterval(stopwatchInterval);
    stopwatchInterval = null;
  }
  if (stopwatchElement) {
    stopwatchElement.textContent = elapsedSeconds !== null ? `⏱ ${elapsedSeconds}s` : '';
  }

  if (dialog) {
    if (typeof dialog.close === 'function') {
      dialog.close();
    } else {
      dialog.removeAttribute('open');
    }
  }

  if (announcer) {
    announcer.setAttribute('aria-live', 'assertive');
    announcer.textContent = '';
    const message = confirmed
      ? 'Refill approved. The agent is submitting the refill order.'
      : 'Refill denied. No order was submitted and no pharmacy records were changed.';
    setTimeout(() => {
      announcer.textContent = message;
    }, 100);
  }

  setTimeout(() => {
    if (previousActiveElement && typeof previousActiveElement.focus === 'function') {
      previousActiveElement.focus();
    }
  }, 300);

  if (activeResolve) {
    const res = activeResolve;
    activeResolve = null;
    res({
      confirmed,
      reason: note,
      timestamp: new Date().toISOString(),
      responseTimeSeconds: elapsedSeconds,
    });
  }

  setTimeout(() => {
    if (announcer) {
      announcer.setAttribute('aria-live', 'polite');
    }
  }, 3000);
}

